language: perl
install: cpanm --installdeps --notest --verbose .
before_install:
  - perlbrew install-cpanm -f
  - perl Makefile.PL | cpanm --notest
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
